vim.api.nvim_set_keymap('n', "<Leader>h", ":wincmd h<CR>", { silent = true, noremap=true })
vim.api.nvim_set_keymap('n', "<Leader>j", ":wincmd j<CR>", { silent = true, noremap=true })
vim.api.nvim_set_keymap('n', "<Leader>k", ":wincmd k<CR>", { silent = true, noremap=true })
vim.api.nvim_set_keymap('n', "<Leader>l", ":wincmd l<CR>", { silent = true, noremap=true })
vim.api.nvim_set_keymap('n', "<Leader>wv", ":vs<CR>", { silent = true , noremap=true})
vim.api.nvim_set_keymap('n', "<Leader>wh", ":split<CR>", { silent = true , noremap=true})
vim.api.nvim_set_keymap('n', "<Leader>=", ":vertical resize +5<CR>", { silent = true, noremap=true })
vim.api.nvim_set_keymap('n', "<Leader>-", ":vertical resize -5<CR>", { silent = true, noremap=true })
vim.api.nvim_set_keymap('n', "<Leader>+", "<C-w>=", { silent = true, noremap=true })
