vim.api.nvim_set_keymap("n", "<Leader>nt", ":tabnew<CR>", {silent = true, noremap=true})
vim.api.nvim_set_keymap("n", "<Leader>ct", ":tabclose<CR>", {silent = true, noremap=true})
vim.api.nvim_set_keymap("n", "<Leader>1", "1gt", {silent = true, noremap=true})
vim.api.nvim_set_keymap("n", "<Leader>2", "2gt", {silent = true, noremap=true})
vim.api.nvim_set_keymap("n", "<Leader>3", "3gt", {silent = true, noremap=true})
vim.api.nvim_set_keymap("n", "<Leader>4", "4gt", {silent = true, noremap=true})
vim.api.nvim_set_keymap("n", "<Leader>5", "5gt", {silent = true, noremap=true})
vim.api.nvim_set_keymap("n", "<Leader>6", "6gt", {silent = true, noremap=true})
vim.api.nvim_set_keymap("n", "<Leader>7", "7gt", {silent = true, noremap=true})
vim.api.nvim_set_keymap("n", "<Leader>8", "8gt", {silent = true, noremap=true})
vim.api.nvim_set_keymap("n", "<Leader>9", "9gt", {silent = true, noremap=true})
vim.api.nvim_set_keymap("n", "<Leader>10","10gt", {silent = true, noremap=true})
