#!/bin/bash


cd $HOME/yt

filesBefore=$(ls -Al *.webm | wc -l)

notify-send "Downloading playlist..." &&
yt-dlp --rm-cache-dir &&
yt-dlp --add-metadata -i -c --write-subs --write-auto-subs --sub-langs "en.*" -o '%(title)s (%(channel)s).%(ext)s' https://youtube.com/playlist?list=PLcXOGPIImO70Uy0MZ8pz0yuzqGccttClJ &&

filesAfter=$(ls -Al *.webm | wc -l)
newFiles=$(( $filesAfter-$filesBefore ))
notify-send "Downloaded $newFiles videos"

echo -e "\n=============================== REMOVING OLD FILES =====================================\n"

notify-send "Removing old videos..."
python $HOME/linux-config/scripts/ytremove.py
notify-send "Old videos removed"
exit 0
