#!/bin/bash

config=$(echo -e "xmonad\nxmobar\npicom\nmpv\ndunst\nconky\nneomutt\ndoom emacs\nyoutube-viewer\nalacritty\nqutebrowser\ndmenu\nranger" | dmenu -i -p "Select config file: ")

case "$config" in
	xmonad) alacritty -e nvim "$HOME/.xmonad/xmonad.hs" ;;
	xmobar) alacritty -e nvim "$HOME/.config/xmobar/xmobarrc" ;;
	picom) alacritty -e nvim "$HOME/.config/picom/picom.conf" ;;
	mpv) alacritty -e nvim "$HOME/.config/mpv/" ;;
	dunst) alacritty -e nvim "$HOME/.config/dunst/dunstrc" ;;
	conky) alacritty -e nvim "$HOME/.config/conky/conky.conf" ;;
	neomutt) alacritty -e nvim "$HOME/.config/mutt/muttrc" ;;
	doom) alacritty -e nvim "$HOME/.doom.d" ;;
	youtube-viewer) alacritty -e nvim "$HOME/.config/youtube-viewer/youtube-viewer.conf" ;;
	alacritty) alacritty -e nvim "$HOME/.config/alacritty/alacritty.yml" ;;
	kitty) alacritty -e nvim "$HOME/.config/kitty/kitty.conf" ;;
	dmenu) alacritty -e nvim "$HOME/linux-config/dmenu-5.0/config.h" ;;
	ranger) alacritty -e nvim "$HOME/.config/ranger";;
	qutebrowser) alacritty -e nvim "$HOME/.config/qutebrowser/config.py";;
esac
