#!/bin/bash

# Turn on bluetooth service
bluetoothctl power on

# Get device info
devices=`bluetoothctl devices | dmenu -l 5 -p "Select device: "`
deviceName=`echo $devices | awk -F " " '{$1=$2="";print $0}'`
deviceNumber=`echo $devices| awk -F " " '{print $2}'`

# send notification and connect to selected device
[ "$deviceName" = "" ] || bluetoothctl connect $deviceNumber && exit 1
