#!/usr/bin/bash

# Defining location of bookmarks file
BMFILE="$HOME/.config/qutebrowser/bookmarks/urls"

# Defining location of quickmarks file
QMFILE="$HOME/.config/qutebrowser/quickmarks"

# Defining the location of history databaase
HISTDB="$HOME/.local/share/qutebrowser/history.sqlite"

# A seperator that will appear between quickmarks, bookmarks and history urls
SEPERATOR="----------" 

# Read array of options to choose
readarray -t bmarks < "$BMFILE"
readarray -t qmarks < "$QMFILE"

# Sort the bookmark, quickmark and history lists so that the url is the last field
# We will awk print the last field later
# History list is formed by greping "http" from the history table.
bmlist=$(printf '%s\n' "${bmarks[@]}" | awk '{print $2" - )
