#!/bin/bash


echo "============= STATUS ============"
git status &&
echo "============ ADDING FILES ======="
read -e -n 1 -p "Add all files [Y/n]: " addAllFiles
case "$addAllFiles" in 
	"y") git add .  ;;
	"") git add . ;;
	"n") 
		read -e -p "Enter files to add: " filestoAdd
		git add $filestoAdd
		;;
esac
echo "============ COMMITTING FILES ==="
read -e -p "Enter commit message [default='Updating files']: " msg
if [ "$msg" = "" ];
then
	git commit -m "Updating files"
else
	git commit -m "$msg" 
fi
echo "============ PUSHING TO GITHUB =="
read -e -p "Enter branch [default=master]: " branch
if [ "$branch" = "" ];
then
	git push origin master;
   	exit 1;
else
	git push origin $branch;
	exit 1;
fi
