#!/bin/bash

BASEDIR="/home/shawn/linux-config"

read -n1 -p "Install yay [Y/n] : " install
if [ "${install^^}" = "Y" ] || [ "${install^^}" = "" ] 
then
	git clone https://aur.archlinux.org/yay-git.git ${HOME}/yay-git
	cd yay-git
	makepkg -si
else
	echo "\nSkipping xmonad & xmobar...\n"
fi

read -n1 -p "Install xmonad & xmobar along with config files & its dependencies [Y/n] : " install
if [ "${install^^}" = "Y" ] || [ "${install^^}" = "" ] 
then

	sudo pacman -S xmonad xmonad-contrib xmobar base-devel xdotool
	yay -S ttf-font-awesome nerd-fonts-mononoki lux 

	echo "setting up xmonad configs..."
	rm -rf ${HOME}/.xmonad
	ln -s ${BASEDIR}/.xmonad ${HOME}/
	rm -rf ${HOME}/.config/xmobar
	ln -s ${BASEDIR}/.config/xmobar ${HOME}/.config/
else
	echo "\nSkipping xmonad & xmobar...\n"
fi


read -n1 -p "Install dmenu along with config files [Y/n] : " install
if [ "${install^^}" = "Y" ] || [ "${install^^}" = "" ] 
then
	sudo pacman -S dmenu
	echo "setting up dmenu configs..."
	cd ${BASEDIR}/dmenu-5.0
	sudo make install
else
	echo "\nSkipping dmenu...\n"
fi

read -n1 -p "Install kitty along with config files [Y/n] : " install
if [ "${install^^}" = "Y" ] || [ "${install^^}" = "" ] 
then
	sudo pacman -S kitty
	echo "setting up kitty configs..."
	rm -rf ${HOME}/.config/kitty
	ln -s ${BASEDIR}/.config/kitty ~/.config/
else
	echo "\nSkipping dmenu...\n"
fi

read -n1 -p "Setup bash along with config files & dependencies [Y/n] : " install
if [ "${install^^}" = "Y" ] || [ "${install^^}" = "" ] 
then
	echo "installing bash settings..."
	sudo pacman -S neofetch bash-completion python-pip exa 
	yay -S devour
	pip install powerline-shell
	rm ${HOME}/.bashrc
	ln -s ${BASEDIR}/.bashrc ~/.bashrc
else
	echo "\nSkipping bash configuration...\n"
fi

read -n1 -p "Install vifm along with config files & dependencies [Y/n] : " install
if [ "${install^^}" = "Y" ] || [ "${install^^}" = "" ] 
then
	echo "installing vifm..."
	sudo pacman -S vifm
	rm -rf ${HOME}/.config/vifm
	ln -s ${BASEDIR}/.config/vifm ~/.config/
else
	echo "\nSkipping vifm...\n"
fi

read -n1 -p "Install vim along with config files & dependencies [Y/n] : " install
if [ "${install^^}" = "Y" ] || [ "${install^^}" = "" ] 
then
	echo "installing vim..."
	sudo pacman -S vim
	rm ${HOME}/.vimrc
	ln -s ${BASEDIR}/.vimrc ~/.vimrc
else
	echo "\nSkipping vim...\n"
fi

read -n1 -p "Install qutebrowser along with config files & dependencies [Y/n] : " install
if [ "${install^^}" = "Y" ] || [ "${install^^}" = "" ] 
then
	echo "installing qutebrowser..."
	sudo pacman -S qutebrowser
	rm -rf ${HOME}/.config/qutebrowser
	ln -s ${BASEDIR}/.config/qutebrowser ~/.config/
else
	echo "\nSkipping qutebrowser...\n"
fi
