#!/bin/bash

BASEDIR="/home/shawn/linux-config"

read -n1 -p "Install xmonad and xmobar along with config files [Y/n] : " install
if [ "${install^^}" = "Y" ] || [ "${install^^}" = "" ] 
then
	sudo pacman -S xmonad xmonad-contrib xmobar
	echo "setting up xmonad configs..."
	rm -rf ${HOME}/.xmonad
	ln -s ${BASEDIR}/.xmonad ${HOME}/
	rm -rf ${HOME}/.config/xmobar
	ln -s ${BASEDIR}/.config/xmobar ${HOME}/.config/
else
	echo "\nSkipping xmonad & xmobar...\n"
fi


read -n1 -p "Install dmenu along with config files [Y/n] : " install
if [ "${install^^}" = "Y" ] || [ "${install^^}" = "" ] 
then
	sudo pacman -S dmenu
	echo "setting up dmenu configs..."
	cd ${BASEDIR}/dmenu-5.0
	sudo make install
else
	echo "\nSkipping dmenu...\n"
fi

read -n1 -p "Install kitty along with config files [Y/n] : " install
if [ "${install^^}" = "Y" ] || [ "${install^^}" = "" ] 
then
	sudo pacman -S kitty
	echo "setting up kitty configs..."
	rm -rf ${HOME}/.config/kitty
	ln -s ${BASEDIR}/kitty ~/.config/
else
	echo "\nSkipping dmenu...\n"
fi
# echo "Installing vim configs..."
# rm ${HOME}/.vimrc
# ln -s ${BASEDIR}/.vimrc ~/.vimrc

# echo "Installing dmenu..."
# cd ${BASEDIR}/dmenu-5.0
# sudo make install

# echo "Installing doom emacs configs..."
# ln -s ${BASEDIR}/doom ~/
# mv ~/doom ~/.doom.d

# echo "Installing kitty configs..."
# rm -rf ${HOME}/.config/kitty
# ln -s ${BASEDIR}/kitty ~/.config/

# echo "installing qutebrowser configs..."
#  rm -rf ${HOME}/.config/qutebrowser
# ln -s ${BASEDIR}/qutebrowser ~/.config/

# echo "installing bash settings..."
# sudo pacman -S neofetch
# rm ${HOME}/.bashrc
# ln -s ${BASEDIR}/.bashrc ~/.bashrc