#!/bin/bash

MOVIE_DIR=$HOME/personal/movies
selected=$(ls $MOVIE_DIR | dmenu -i -p "Select movie: ")
[ -z $selected ] && exit 0

secondSelected=$(ls $MOVIE_DIR/$selected | dmenu -i -p "Select movie: ")
[ -z $secondSelected ] && exit 0

if [ -d "$MOVIE_DIR/$selected/$secondSelected" ]; then
	ls $MOVIE_DIR/$selected/$secondSelected | dmenu -i -p "Select movie: " | xargs -I {} mpv $MOVIE_DIR/$selected/$secondSelected/{} && exit 0
else 
	mpv $MOVIE_DIR/$selected/$secondSelected && exit 0
fi

exit 0
