#!/usr/bin/env bash

function doAction () {
	case "$1" in 
		shutdown) systemctl poweroff ;;
		reboot) systemctl reboot ;;
		suspend) systemctl suspend ;;
		logout) pkill xmonad ;;
		display) xset dpms force off ;;
	esac
}

export -f doAction

echo -e "shutdown\nreboot\nlogout\nsuspend\nturn off display" | dmenu | xargs -d' ' -I {} bash -c "doAction {}" && exit 0
