#!/bin/bash


cd $HOME/yt

filesBefore=$(ls -Al | wc -l)

notify-send "Downloading playlist..." &&
yt-dlp -o '%(title)s.%(ext)s' https://youtube.com/playlist?list=PLcXOGPIImO70Uy0MZ8pz0yuzqGccttClJ &&

filesAfter=$(ls -Al | wc -l)
newFiles=$(( $filesAfter-$filesBefore ))

notify-send "Downloaded $newFiles videos"
exit 0
