#!/bin/bash

cd $HOME/yt
video=`ls --sort=time *.webm | awk -F ".web" '{print $1}' | dmenu -i -l 20 -p "Select video: "`
subtitleFile=`ls *.vtt | grep -e "$video"`

[ $subtitleFile = "" ] || mpv "$video.webm" --speed=1.25 --volume=50 --sub-auto="fuzzy"
